# Replication code for project "Impact of R&D Spending on COVID-19 Mortality by Country" by Ramzi CHARIAG. 


# set path of stata executable here
STATA 			= C:/users/Ramzi/Stata-MP-16.0/stata-se -b
Output_DIR 		= ../Results
# LOG_DIR			= ../log
DATA_DIR		= ../Data/Transformed
CODE_DIR		= .

$(STATA) do master_do
